# configurations
# 详情请参考：https://halo.run/develop/theme.html#settings-yaml
genernal:
  label: 通用设置
  items:
    home_title:
      name: home_title
      label: 首页展示博客名
      type: text
      placeholder: "用于首页展示名字"
      description: "注意：如填写，会覆盖原有博客名"
    home_description:
      name: home_description
      label: 网站slogan
      type: text
      placeholder: "用于首页描述"
    posts_style:
      name: posts_style
      label: 首页文章列表展示风格
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 卡片
        - value: false
          label: 列表
    list_show_date:
      name: list_show_date
      label: 列表样式下的文章默认封面是否是日期
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    show_popular:
      name: show_popular
      label: 列表风格下是否展示热门文章
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    card_hover_summary:
      name: card_hover_summary
      label: 卡片风格首页是否展示文章简介
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    home_cover:
      name: home_cover
      label: 首页背景
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    enabled_index_cover_height:
      name: enabled_index_cover_height
      label: 首页全屏图片
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    auto_night_mode:
      name: auto_night_mode
      label: 自动夜晚模式
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
      description: "这里会根据浏览器主题改变"
    right_corner_circle:
      name: right_corner_circle
      label: 开启右下角按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    default_hide_menu:
      name: default_hide_menu
      label: 打开展示收缩菜单按钮
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
      description: "打开后会默认收缩菜单"
    open_night_mode:
      name: open_night_mode
      label: 开启夜晚模式
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    card_random_cover_list:
      name: card_random_cover_list
      label: 随机封面图片列表，分号分割
      type: textarea
      description: "英文分号(;)分割。注意，这里面填写了图片路径则默认开启了随机图片"
    Icp:
      name: Icp
      label: "ICP 备案号"
      type: text
      placeholder: "填入 ICP 备案号，没有则不填. "
    PublicSecurityRecord:
      name: PublicSecurityRecord
      label: "网安备案号"
      type: text
      placeholder: "填入网安备案号代码，没有则不填"
    QR_code_zfb:
      name: QR_code_zfb
      label: "支付宝二维码图片"
      type: attachment
      placeholder: "支付宝收款二维码链接，不填不显示"
    QR_code_wx:
      name: QR_code_wx
      label: "微信二维码图片"
      type: attachment
      placeholder: "微信收款二维码链接，不填不显示"
head_img:
  label: 网页首部图片
  items:
    archives_patternimg:
      name: archives_patternimg
      label: 归档页面默认头部图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    links_patternimg:
      name: links_patternimg
      label: 友情链接页面默认头部图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    tag_patternimg:
      name: tag_patternimg
      label: 标签页面默认头部图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    categories_patternimg:
      name: categories_patternimg
      label: 分类页面默认头部图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    journals_patternimg:
      name: journals_patternimg
      label: 日志下文章页面默认头部图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    photos_patternimg:
      name: photos_patternimg
      label: 相册页面默认头部图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    search_patternimg:
      name: search_patternimg
      label: 搜索结果默认头部图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    links_placeholder:
      name: links_placeholder
      label: 友情链接默认用户头像
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
post:
  label: 文章页
  items:
    post_toc:
      name: post_toc
      label: 是否展示目录
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_nepre:
      name: post_nepre
      label: 文章页是否显示上一篇和下一篇文章
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enabled_mathjax:
      name: enabled_mathjax
      label: 是否展示公式
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enable_code_highlight:
      name: enable_code_highlight
      label: 是否开启代码高亮
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enable_code_lineNumber:
      name: enable_code_lineNumber
      label: 代码是否展示行号(需先开启代码高亮)
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    collpaseCode:
      name: collpaseCode
      label: 是否开启代码折叠
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    more_lang_code:
      name: more_lang_code
      label: 更多代码高亮
      type: radio
      data-type: bool
      default: false
      decription: "如果目前代码高亮不支持,可以尝试开启此开关"
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    idea_code_style:
      name: idea_code_style
      label: IDEA代码风格
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    code_style:
      name: code_style
      label: 代码风格
      type: select
      data-type: string
      default: "tomorrow-night-bright"
      description: "代码风格"
      options:
        - value: "tomorrow-night-bright"
          label: "tomorrow"
        - value: "atelier-lakeside-light"
          label: "atelier"
        - value: "atom-one-light"
          label: "atom"
        - value: "github"
          label: "github"
        - value: "github-gist"
          label: "github-gist"
        - value: "kimbie.light"
          label: "kimbie"
        - value: "paraiso-light"
          label: "paraiso"
        - value: "androidstudio"
          label: "androidstudio"
#    enabled_mermaid:
#      name: enabled_mermaid
#      label: Mermaid
#      type: radio
#      data-type: bool
#      default: false
#      options:
#        - value: true
#          label: 开启
#        - value: false
#          label: 关闭
title:
  label: 自定义页面标题
  items:
    links_title:
      name: links_title
      label: 友链页面标题
      type: text
      default: 友链
    jounarls_title:
      name: jounarls_title
      label: 日志页面标题
      type: text
      default: 日志
    tags_title:
      name: tags_title
      label: 标签页面标题
      type: text
      default: 标签列表
    categories_title:
      name: categories_title
      label: 分类列表页面标题
      type: text
      default: 分类列表
    achieve_title:
      name: achieve_title
      label: 归档页面标题
      type: text
      default: 归档
    photos_title:
      name: photos_title
      label: 相册页面标题
      type: text
      default: 相册
social:
  label: 社交网络
  items:
    sina:
      name: sina
      label: 新浪微博
      type: text
      placeholder: "用于展示底部新浪微博社交信息"
      description: "新浪微博主页链接"
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: "用于展示底部 Telegram 社交信息"
      description: "Telegram 用户名"
    twitter:
      name: twitter
      label: Twitter
      type: text
      placeholder: "用于展示底部 Twitter 社交信息"
      description: "Twitter 主页链接"
    qq:
      name: qq
      label: 腾讯 QQ
      type: text
      placeholder: "用于展示底部 QQ 社交信息"
      description: "QQ 号码"
    github:
      name: github
      label: Github
      type: text
      placeholder: "用于展示底部 Github 社交信息"
      description: "GitHub 主页链接"
    zhihu:
      name: zhihu
      label: 知乎
      type: text
      placeholder: "用于展示底部知乎社交信息"
      description: "知乎主页链接"
    mail:
      name: mail
      label: 邮箱
      type: text
      placeholder: "用于展示底部邮箱社交信息"
      description: "邮箱地址"
    rss:
      name: rss
      label: 订阅按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
experimental:
  label: 高级功能
  items:
    pjax_enabled:
      name: pjax_enabled
      label: 全局 Pjax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enable_image_view:
      name: enable_image_view
      label: 是否启用图片预览（点击全屏）
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    enable_photo:
      name: enable_photo
      label: 是否启用相册
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

other:
  label: 其他
  items:
    TimeStatistics:
      name: TimeStatistics
      label: "站点运行时间统计"
      type: text
      description: "填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00"
    visit_statistics:
      name: visit_statistics
      label: 用户访问统计
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    Aplayer:
      name: Aplayer
      label: Aplayer吸底播放器
      type: text
      placeholder: "网易云歌单id"
      description: "网易云歌单id, 比如: 60198. "
    xiang_ying_xiong_zhi_jing:
      name: xiang_ying_xiong_zhi_jing
      label: 向英雄致敬, 愿精神长存
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
      description: "惟愿此功能永远不会被使用"
    other_script_file:
      name: other_script_file
      label: 作为插件引入的js脚本文件
      type: textarea
      default: ""
    common_js:
      name: common_js
      label: 作为插件需要执行的js脚本内容
      type: textarea
      default: ""
      description: "同时只是加载和pjax执行该脚本"
