# configurations
# 详情请参考：https://halo.run/develop/theme.html#settings-yaml
genernal:
  label: 通用设置
  items:
    home_title:
      name: home_title
      label: 首页展示博客名
      type: text
      placeholder: "用于首页展示名字"
      description: "注意：如填写，会覆盖原有博客名"
    home_description:
      name: home_description
      label: 网站slogan
      type: text
      placeholder: "用于首页描述"
    show_logo:
      name: show_logo
      label: 是否展示Logo
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 是
        - value: false
          label: 否  
    posts_style:
      name: posts_style
      label: 首页文章列表展示风格
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 卡片
        - value: false
          label: 列表
    show_popular:
      name: show_popular
      label: 列表风格下是否展示热门文章
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    card_hover_summary:
      name: card_hover_summary
      label: 卡片风格首页是否展示文章简介
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    home_cover:
      name: home_cover
      label: 首页背景
      type: attachment
      default: https://cdn.jsdelivr.net/gh/xzzai/static@master/uPic/default-bg.jpg
    enabled_index_cover_height:
      name: enabled_index_cover_height
      label: 首页全屏图片
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    card_random_cover_list:
      name: card_random_cover_list
      label: 随机封面图片列表，分号分割
      type: textarea
      description: "英文分号(;)分割。注意，这里面填写了图片路径则默认开启了随机图片"
    Icp:
      name: Icp
      label: "ICP 备案号"
      type: text
      placeholder: "填入 ICP 备案号，没有则不填. "
    PoliceSecurityRecordCode:
      name: PoliceSecurityRecordCode
      label: "网安备案号编码"
      type: text
      placeholder: "网安备案号编码，用于链接跳转"  
    PublicSecurityRecord:
      name: PublicSecurityRecord
      label: "网安备案号"
      type: text
      placeholder: "填入网安备案号文字"
    QR_code_zfb:
      name: QR_code_zfb
      label: "支付宝二维码图片"
      type: attachment
      placeholder: "支付宝收款二维码链接，不填不显示"
    QR_code_wx:
      name: QR_code_wx
      label: "微信二维码图片"
      type: attachment
      placeholder: "微信收款二维码链接，不填不显示"
head_img:
  label: 网页首部图片
  items:
    archives_patternimg:
      name: archives_patternimg
      label: 归档页面默认头部图
      type: attachment
    links_patternimg:
      name: links_patternimg
      label: 友情链接页面默认头部图
      type: attachment
    tag_patternimg:
      name: tag_patternimg
      label: 标签页面默认头部图
      type: attachment
    categories_patternimg:
      name: categories_patternimg
      label: 分类页面默认头部图
      type: attachment
    journals_patternimg:
      name: journals_patternimg
      label: 日志下文章页面默认头部图
      type: attachment
    photos_patternimg:
      name: photos_patternimg
      label: 相册页面默认头部图
      type: attachment
    search_patternimg:
      name: search_patternimg
      label: 搜索结果默认头部图
      type: attachment
    links_placeholder:
      name: links_placeholder
      label: 友情链接默认用户头像
      type: attachment
post:
  label: 文章页
  items:
    post_toc:
      name: post_toc
      label: 是否展示目录
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_nepre:
      name: post_nepre
      label: 文章页是否显示上一篇和下一篇文章
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
title:
  label: 自定义页面标题
  items:
    links_title:
      name: links_title
      label: 友链页面标题
      type: text
      default: 友链
    jounarls_title:
      name: jounarls_title
      label: 日志页面标题
      type: text
      default: 日志
    tags_title:
      name: tags_title
      label: 标签页面标题
      type: text
      default: 标签列表
    categories_title:
      name: categories_title
      label: 分类列表页面标题
      type: text
      default: 分类列表
    achieve_title:
      name: achieve_title
      label: 归档页面标题
      type: text
      default: 归档
    photos_title:
      name: photos_title
      label: 相册页面标题
      type: text
      default: 相册
social:
  label: 社交网络
  items:
    github:
      name: github
      label: Github
      type: text
      placeholder: "GitHub"
      description: "GitHub 主页链接"
    mail:
      name: mail
      label: 邮箱
      type: text
      placeholder: "邮箱"
      description: "邮箱地址"
    zhihu:
      name: zhihu
      label: 知乎
      type: text
      placeholder: "知乎"
      description: "知乎个人主页地址" 
    weibo:
      name: weibo
      label: 微博
      type: text
      placeholder: "微博"
      description: "微博个人主页地址"
    rss:
      name: rss
      label: 订阅按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
experimental:
  label: 高级功能
  items:
    pjax_enabled:
      name: pjax_enabled
      label: 全局 Pjax
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭

other:
  label: 其他
  items:
    TimeStatistics:
      name: TimeStatistics
      label: "站点运行时间统计"
      type: text
      description: "填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00"
    visit_statistics:
      name: visit_statistics
      label: 用户访问统计
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    xiang_ying_xiong_zhi_jing:
      name: xiang_ying_xiong_zhi_jing
      label: 向英雄致敬, 愿精神长存
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
      description: "惟愿此功能永远不会被使用"
    other_script_file:
      name: other_script_file
      label: 作为插件引入的js脚本文件
      type: textarea
      default: ""
    common_js:
      name: common_js
      label: 作为插件需要执行的js脚本内容
      type: textarea
      default: ""
      description: "同时只是加载和pjax执行该脚本"
